### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by FrankC01** [hashblock/solana-cli-program-template#1]
@mvines From a testing perspective, I have completed implementation of a sunny day integration test through the program instructions. These are not options in the CLI, yet....

If you want to take a look and provide any feedback before I continue at this point please feel free. Do not spare the lash :)... still in learning curve and it will help.

**Comment by mvines** [comment]
Thanks, I linked to this template from https://github.com/mvines/solana-cli-template#want-batteries-included !

**Comment by FrankC01** [comment]
Great, I'll leave you with access as is should something come up.
